apiVersion: v1
kind: Namespace
metadata:
  name: ai-lab
  labels:
    name: ai-lab
    environment: demo
    project: ai-lab
    # Pod Security Standards
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    environment: demo
    project: ai-lab
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: demo
    project: ai-lab
